"""PostgreSQL persistence layer for the gateway.

The app speaks to a document-style store interface (plain dicts in/out),
implemented by ``PostgresStore`` on top of SQLAlchemy Core with the psycopg 3
driver. PostgreSQL is the **only** production storage engine, configured
with one single-line connection URL:

  DATABASE_URL=postgresql+psycopg://user:pass@localhost:5432/mfs_gateway

Plain ``postgresql://`` / ``postgres://`` URLs are auto-upgraded to the
psycopg driver. For tests/CI the identical store code runs against an
in-memory SQLite database (``DATABASE_URL=sqlite://``) — same SQLAlchemy
code path, no PostgreSQL server required for tests/CI.

Money is integer paisa; timestamps are UTC ISO-8601 strings (lexicographic
ordering matches chronological ordering for the formats we write).
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone


class DuplicateError(Exception):
    """Raised on unique-constraint violations (trxid, email, order id...)."""


def utcnow_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


DEFAULT_SETTINGS = {
    "gateway_name": "UniquePay BD",
    "session_ttl_minutes": "15",
    "max_verify_attempts": "10",
    "provider_wallets": json.dumps({
        "bkash":  {"number": "01700-000000", "type": "Personal", "enabled": True},
        "nagad":  {"number": "01800-000000", "type": "Personal", "enabled": True},
        "rocket": {"number": "01900-0000008", "type": "Agent",   "enabled": True},
        "upay":   {"number": "01600-000000", "type": "Personal", "enabled": True},
        "tap":    {"number": "01500-000000", "type": "Personal", "enabled": False},
        "meghna": {"number": "01300-000000", "type": "Personal", "enabled": False},
    }),
}


class Store:
    """Interface contract (documented; implemented by PostgresStore)."""

    # --- lifecycle ---------------------------------------------------------
    def init(self, app) -> None:
        """Create tables/indexes, seed default settings + deterministic admin."""
        raise NotImplementedError

    def close(self) -> None:  # pragma: no cover - trivial
        pass

    # --- settings / audit --------------------------------------------------
    def get_setting(self, key: str, default: str = "") -> str: ...
    def set_setting(self, key: str, value: str) -> None: ...
    def all_settings(self) -> dict: ...
    def audit(self, actor: str, action: str, meta: str = "") -> None: ...
    def list_audit(self, limit: int = 100) -> list: ...

    # --- admins ------------------------------------------------------------
    def find_admin(self, username: str): ...
    def upsert_admin(self, username: str, password_hash: str) -> None: ...
    def set_admin_password(self, username: str, password_hash: str) -> None: ...

    # --- merchants ---------------------------------------------------------
    def create_merchant(self, email: str, name: str, password_hash: str) -> int: ...
    def find_merchant_by_email(self, email: str): ...
    def get_merchant(self, merchant_id: int): ...
    def set_merchant_password(self, merchant_id: int, password_hash: str) -> None: ...
    def set_merchant_status(self, merchant_id: int, status: str) -> None: ...
    def count_merchants(self) -> int: ...
    def list_merchants_enriched(self) -> list: ...

    # --- api keys ----------------------------------------------------------
    def create_api_key(self, merchant_id: int, key_id: str,
                       secret: str, label: str) -> int: ...
    def find_active_key(self, key_id: str): ...
    def list_keys_for_merchant(self, merchant_id: int) -> list: ...
    def list_all_keys_enriched(self) -> list: ...
    def set_key_status(self, key_pk: int, status: str,
                       merchant_id: int | None = None) -> int: ...
    def touch_key(self, key_pk: int, when: str) -> None: ...
    def count_keys(self, merchant_id: int) -> int: ...

    # --- devices -----------------------------------------------------------
    def create_device(self, device_id: str, name: str, secret: str) -> None: ...
    def find_active_device(self, device_id: str): ...
    def list_devices(self) -> list: ...
    def set_device_status(self, device_id: str, status: str) -> None: ...
    def touch_device(self, device_id: str, when: str) -> None: ...

    # --- sms ledger --------------------------------------------------------
    def insert_sms(self, provider: str, sender: str, amount_paisa: int,
                   trxid: str, device_id: str, sms_timestamp: str,
                   raw_hash: str) -> str: ...        # "stored" | "duplicate"
    def find_sms_by_trxid(self, trxid: str): ...
    def get_sms(self, sms_id: int): ...
    def claim_sms(self, sms_id: int, session_id: str) -> bool: ...
    def release_sms(self, sms_id: int) -> None: ...
    def list_sms_since(self, since_id: int, limit: int = 150) -> list: ...
    def list_sms_recent(self, limit: int = 12) -> list: ...
    def sms_stats(self) -> dict: ...

    # --- payment sessions --------------------------------------------------
    def create_session(self, data: dict) -> None: ...
    def find_session(self, session_id: str): ...
    def find_session_by_order(self, merchant_id: int, order_id: str): ...
    def mark_session_expired(self, session_id: str) -> int: ...
    def increment_attempts(self, session_id: str) -> None: ...
    def mark_session_paid(self, session_id: str, provider: str,
                          payer_wallet: str, trxid: str, paid_at: str) -> None: ...
    def reset_session_to_pending(self, session_id: str) -> None: ...
    def payment_stats(self, merchant_id: int | None = None,
                      since_iso: str | None = None) -> dict: ...
    def count_pending_sessions(self, merchant_id: int) -> int: ...
    def list_sessions(self, merchant_id: int | None = None,
                      limit: int = 100) -> list: ...       # enriched, newest first
    def list_paid_recent(self, limit: int = 12) -> list: ...  # enriched


DEFAULT_DATABASE_URL = "postgresql+psycopg://localhost:5432/mfs_gateway"


def make_store(app) -> Store:
    """Build the PostgreSQL store. Single-line config: DATABASE_URL.

    * Production:  DATABASE_URL=postgresql+psycopg://user:pass@host/db
      (plain ``postgresql://`` / ``postgres://`` URLs are auto-upgraded).
    * Tests/CI:    DATABASE_URL=sqlite://  — in-memory SQLite through the
      same SQLAlchemy code path (restricted sandboxes with no PostgreSQL
      server; never in production).
    """
    from . import postgres_store

    url = os.environ.get("DATABASE_URL", DEFAULT_DATABASE_URL)
    return postgres_store.PostgresStore(url=url)
